version: "2"
services:
    client:
        build: ./client
        image: paradise_papers_client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
        networks:
            - rpnet
    api:
        build: ./api
        image: paradise_papers_api
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /api/node_modules
        depends_on:
            - mongodb
        networks:
            - rpnet
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data_node:/data/db
        ports:
            - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: pass1234
        command: "mongod --auth"
        networks:
            - rpnet 
networks:
    rpnet:
        driver: bridge