version: "2"
services:
    client:
        build: ./client
        image: paradise_papers_client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
        networks:
            - rpnet
    api:
        build: ./api
        image: paradise_papers_api
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /api/node_modules
        # depends_on:
        #     - mongodb
        networks:
            - rpnet
    # mongodb:make
    #     image: mongo
    #     restart: always
    #     container_name: paradise_papers_mongodb
    #     volumes:
    #         - ./data_node:/data/db
    #         - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #     ports:
    #         - 27017:27017
    #     environment:
    #       MONGO_INITDB_ROOT_USERNAME: root
    #       MONGO_INITDB_ROOT_PASSWORD: pass1234
    #     command: "mongod --auth"
    #     networks:
    #         - rpnet 
    grapdb:
      image: neo4j
      restart: always
      container_name: paradise_papers_neo4j
      volumes:
        - ./graphdb_data/data:/data
        - ./graphdb_data/logs:/logs
        - ./sample_data:/var/lib/neo4j/import
      ports:
        - 7474:7474
        - 7687:7687
      networks:
        - rpnet
networks:
    rpnet:
        driver: bridge